"""Materialize vdirsyncer config from the config store."""

from __future__ import annotations

import json
import logging
from pathlib import Path

log = logging.getLogger(__name__)

VDIRSYNCER_CONFIG_PATH = Path("/tmp/mpa-vdirsyncer-config")
VDIRSYNCER_XDG_DIR = Path("/tmp/mpa-vdirsyncer-xdg")
VDIRSYNCER_XDG_CONFIG_PATH = VDIRSYNCER_XDG_DIR / "vdirsyncer" / "config"


def vdirsyncer_env() -> dict[str, str]:
    return {
        "VDIRSYNCER_CONFIG": str(VDIRSYNCER_CONFIG_PATH),
        "XDG_CONFIG_HOME": str(VDIRSYNCER_XDG_DIR),
    }


def _sanitize_slug(value: str, fallback: str) -> str:
    slug = "".join(ch.lower() if ch.isalnum() else "-" for ch in value.strip())
    slug = "-".join(part for part in slug.split("-") if part)
    return slug or fallback


def _render_provider(provider: dict[str, str], idx: int, taken: set[str]) -> tuple[str, str] | None:
    name = str(provider.get("name", "")).strip()
    provider_type = str(provider.get("type", "carddav")).strip() or "carddav"
    base_slug = _sanitize_slug(name or f"provider-{idx + 1}", f"provider-{idx + 1}")
    slug = base_slug
    if slug in taken:
        slug = f"{base_slug}-{idx + 1}"
    taken.add(slug)

    if provider_type == "google_contacts":
        client_id = str(provider.get("client_id", "")).strip()
        client_secret = str(provider.get("client_secret", "")).strip()
        if not (client_id and client_secret):
            return None
        local = f"contacts_local_{slug}"
        remote = f"contacts_google_{slug}"
        pair = f"contacts_{slug}"
        local_path = f"~/.local/share/vdirsyncer/contacts/{slug}/"
        token_path = f"~/.local/share/vdirsyncer/tokens/{slug}_google"
        return (
            pair,
            "\n".join(
                [
                    f"[pair {pair}]",
                    f'a = "{local}"',
                    f'b = "{remote}"',
                    'collections = ["from a", "from b"]',
                    "",
                    f"[storage {local}]",
                    'type = "filesystem"',
                    f'path = "{local_path}"',
                    'fileext = ".vcf"',
                    "",
                    f"[storage {remote}]",
                    'type = "google_contacts"',
                    f'token_file = "{token_path}"',
                    f'client_id = "{client_id}"',
                    f'client_secret = "{client_secret}"',
                ]
            ),
        )

    url = str(provider.get("url", "")).strip()
    username = str(provider.get("username", "")).strip()
    password = str(provider.get("password", "")).strip()
    if not (url and username and password):
        return None
    local = f"contacts_local_{slug}"
    remote = f"contacts_carddav_{slug}"
    pair = f"contacts_{slug}"
    local_path = f"~/.local/share/vdirsyncer/contacts/{slug}/"
    return (
        pair,
        "\n".join(
            [
                f"[pair {pair}]",
                f'a = "{local}"',
                f'b = "{remote}"',
                'collections = ["from a", "from b"]',
                "",
                f"[storage {local}]",
                'type = "filesystem"',
                f'path = "{local_path}"',
                'fileext = ".vcf"',
                "",
                f"[storage {remote}]",
                'type = "carddav"',
                f'url = "{url}"',
                f'username = "{username}"',
                f'password = "{password}"',
            ]
        ),
    )


async def materialize_vdirsyncer_config(config_store) -> bool:
    """Write vdirsyncer config from config DB.

    Returns True if a file was written or removed.
    """
    raw = await config_store.get("contacts.providers")
    if not raw:
        removed = False
        if VDIRSYNCER_CONFIG_PATH.exists():
            VDIRSYNCER_CONFIG_PATH.unlink()
            removed = True
        if VDIRSYNCER_XDG_CONFIG_PATH.exists():
            VDIRSYNCER_XDG_CONFIG_PATH.unlink()
            removed = True
        return removed

    try:
        providers = json.loads(raw)
    except Exception:
        providers = []
    if not isinstance(providers, list):
        providers = []

    blocks: list[str] = [
        "# Auto-generated by the admin UI.\n# Edit via the Contacts tab.",
        "",
        "[general]",
        'status_path = "~/.local/share/vdirsyncer/status/"',
        "",
    ]
    pairs: list[str] = []
    taken: set[str] = set()
    for idx, provider in enumerate(providers):
        if not isinstance(provider, dict):
            continue
        rendered = _render_provider(provider, idx, taken)
        if not rendered:
            continue
        pair_name, body = rendered
        pairs.append(pair_name)
        blocks.append(body)
        blocks.append("")

    if not pairs:
        removed = False
        if VDIRSYNCER_CONFIG_PATH.exists():
            VDIRSYNCER_CONFIG_PATH.unlink()
            removed = True
        if VDIRSYNCER_XDG_CONFIG_PATH.exists():
            VDIRSYNCER_XDG_CONFIG_PATH.unlink()
            removed = True
        return removed

    content = "\n".join(blocks).rstrip() + "\n"
    VDIRSYNCER_CONFIG_PATH.write_text(content)
    VDIRSYNCER_XDG_CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    VDIRSYNCER_XDG_CONFIG_PATH.write_text(content)
    log.info("Materialized vdirsyncer config to %s", VDIRSYNCER_CONFIG_PATH)
    return True
