"""On-demand image generation (issue #55).

A single ``generate_image`` tool backed by one configured provider. The
provider + model are configuration choices, not per-call decisions:

* **openrouter** — Unified Image API (``/api/v1/images``), reuses an existing
  OpenRouter LLM key. Returns base64 (``data[].b64_json``).
* **fal** — pay-as-you-go REST (``https://fal.run/<model>``). Returns a hosted
  URL (``images[].url``) we download.
* **openai** — Images API (``/v1/images/generations``), reuses an existing
  OpenAI LLM key. Returns base64 (``data[].b64_json``).

Disabled by default; enabled + configured from the admin UI. A small SQLite
counter enforces a daily/monthly image cap so a runaway loop can't run up a
bill. Generated bytes are handed back to the channel as native media.
"""

from __future__ import annotations

import base64
import uuid
from datetime import UTC, datetime
from pathlib import Path

import aiosqlite
import httpx

from core.config import Config

# Sensible default model per provider (issue #55). All are user-editable in the
# admin UI; the Test button validates the chosen model before it's relied on.
DEFAULT_MODELS: dict[str, str] = {
    # OpenRouter's image API carries no FLUX models — Google/OpenAI only. Nano
    # Banana is the cheapest available default. (List: GET /api/v1/models.)
    "openrouter": "google/gemini-2.5-flash-image",  # zero new auth, reuses LLM key
    "fal": "fal-ai/flux/schnell",  # ~$0.003, sub-second
    "openai": "gpt-image-1-mini",  # $0.005 low, best text rendering
}

_EXT = {"image/png": "png", "image/jpeg": "jpg", "image/webp": "webp", "image/gif": "gif"}


class ImageGenError(Exception):
    """A provider/config error surfaced to the agent (and the admin Test button)."""


def llm_fallback_key(cfg: Config, provider: str) -> str:
    """Reuse an already-configured LLM key when no dedicated image key is set.

    OpenRouter-as-LLM shows up as an OpenAI-compatible provider whose base URL
    points at openrouter; that's the only honest way to detect it.
    """
    agent = cfg.agent
    if provider == "openai":
        return agent.openai_api_key or ""
    if provider == "openrouter" and "openrouter" in (agent.openai_base_url or "").lower():
        return agent.openai_api_key or ""
    return ""


def resolve_api_key(cfg: Config) -> str:
    ig = cfg.tools.imagegen
    return ig.api_key or llm_fallback_key(cfg, (ig.provider or "").lower())


async def generate(cfg: Config, prompt: str, size: str = "") -> tuple[bytes, str]:
    """Generate one image from config. Returns (bytes, mime_type)."""
    ig = cfg.tools.imagegen
    return await generate_bytes(ig.provider, ig.model, resolve_api_key(cfg), prompt, size)


async def generate_bytes(
    provider: str, model: str, api_key: str, prompt: str, size: str = ""
) -> tuple[bytes, str]:
    """Low-level generate from explicit args (used by the admin Test button too)."""
    provider = (provider or "openrouter").lower()
    if not api_key:
        raise ImageGenError("No API key configured for image generation.")
    model = model or DEFAULT_MODELS.get(provider, "")
    if not model:
        raise ImageGenError(f"Unknown image provider: {provider!r}")
    if not prompt.strip():
        raise ImageGenError("A prompt is required.")
    # Generation is slow (gpt-image ~10-15s); give it room.
    async with httpx.AsyncClient(timeout=httpx.Timeout(180.0)) as client:
        if provider == "openai":
            return await _openai(client, api_key, model, prompt, size)
        if provider == "openrouter":
            return await _openrouter(client, api_key, model, prompt)
        if provider == "fal":
            return await _fal(client, api_key, model, prompt)
    raise ImageGenError(f"Unknown image provider: {provider!r}")


async def _openai(
    client: httpx.AsyncClient, key: str, model: str, prompt: str, size: str
) -> tuple[bytes, str]:
    body: dict = {"model": model, "prompt": prompt, "n": 1}
    if size:
        body["size"] = size
    if model.startswith("gpt-image"):
        body["quality"] = "low"  # cheapest tier; the configured model picks the family
    else:
        # dall-e-* default response_format to "url" (no b64_json); force base64 so
        # the parse below works. gpt-image always returns base64 and rejects this param.
        body["response_format"] = "b64_json"
    r = await client.post(
        "https://api.openai.com/v1/images/generations",
        headers={"Authorization": f"Bearer {key}"},
        json=body,
    )
    _check(r)
    return base64.b64decode(r.json()["data"][0]["b64_json"]), "image/png"


async def _openrouter(
    client: httpx.AsyncClient, key: str, model: str, prompt: str
) -> tuple[bytes, str]:
    r = await client.post(
        "https://openrouter.ai/api/v1/images",
        headers={"Authorization": f"Bearer {key}"},
        json={"model": model, "prompt": prompt},
    )
    _check(r)
    item = r.json()["data"][0]
    return base64.b64decode(item["b64_json"]), item.get("media_type") or "image/png"


async def _fal(client: httpx.AsyncClient, key: str, model: str, prompt: str) -> tuple[bytes, str]:
    r = await client.post(
        f"https://fal.run/{model}",
        headers={"Authorization": f"Key {key}"},
        json={"prompt": prompt, "num_images": 1},
    )
    _check(r)
    img = r.json()["images"][0]
    dl = await client.get(img["url"])
    dl.raise_for_status()
    return dl.content, img.get("content_type") or "image/jpeg"


def _check(r: httpx.Response) -> None:
    """Raise a readable ImageGenError on a non-2xx, digging out the provider message."""
    if r.status_code < 400:
        return
    msg: str | None = None
    try:
        j = r.json()
        err = j.get("error")
        if isinstance(err, dict):
            msg = err.get("message")
        elif isinstance(err, str):
            msg = err
        msg = msg or j.get("detail")
    except Exception:
        msg = None
    # Use only the structured message — never echo the raw body, which could in
    # principle reflect the Authorization header on some gateways (#55 review).
    raise ImageGenError(msg or f"Provider returned HTTP {r.status_code}")


def save(data: bytes, mime: str, directory: str = "data/images") -> str:
    """Persist generated bytes to disk and return the path (issue #55 wants a path)."""
    d = Path(directory)
    d.mkdir(parents=True, exist_ok=True)
    path = d / f"{uuid.uuid4().hex}.{_EXT.get(mime, 'png')}"
    path.write_bytes(data)
    return str(path)


class ImageBudget:
    """Global daily/monthly image-count guardrail, persisted in SQLite.

    ponytail: global (not per-user) and count-only — the guardrail exists to stop
    a runaway/subagent loop running up a bill, which a global cap covers. Per-user
    or spend (USD) caps can layer on later if needed. Month total = SUM over the
    month's daily rows, so there's no separate monthly counter to keep in sync.
    """

    def __init__(self, db_path: str = "data/imagegen.db"):
        self.db_path = db_path

    async def _conn(self) -> aiosqlite.Connection:
        Path(self.db_path).parent.mkdir(parents=True, exist_ok=True)
        db = await aiosqlite.connect(self.db_path)
        await db.execute(
            "CREATE TABLE IF NOT EXISTS image_usage "
            "(day TEXT PRIMARY KEY, count INTEGER NOT NULL DEFAULT 0)"
        )
        return db

    async def usage(self) -> tuple[int, int]:
        """Return (images today, images this month) in UTC."""
        now = datetime.now(UTC)
        day = now.strftime("%Y-%m-%d")
        month = now.strftime("%Y-%m")
        db = await self._conn()
        try:
            cur = await db.execute("SELECT count FROM image_usage WHERE day = ?", (day,))
            today = (await cur.fetchone() or (0,))[0]
            cur = await db.execute(
                "SELECT COALESCE(SUM(count), 0) FROM image_usage WHERE day LIKE ?",
                (f"{month}%",),
            )
            this_month = (await cur.fetchone() or (0,))[0]
            return int(today), int(this_month)
        finally:
            await db.close()

    async def check(self, daily: int, monthly: int) -> str | None:
        """Return an error message if a cap is already reached, else None."""
        if daily <= 0 and monthly <= 0:
            return None
        today, this_month = await self.usage()
        if daily > 0 and today >= daily:
            return f"Daily image budget reached ({today}/{daily}). Resets at 00:00 UTC."
        if monthly > 0 and this_month >= monthly:
            return f"Monthly image budget reached ({this_month}/{monthly})."
        return None

    async def warning(self, daily: int, monthly: int, threshold: float = 0.8) -> str | None:
        """Return a non-blocking heads-up when usage is near (>=80%) a cap, else None."""
        if daily <= 0 and monthly <= 0:
            return None
        today, this_month = await self.usage()
        if daily > 0 and today < daily and today >= daily * threshold:
            return f"Approaching the daily image budget ({today}/{daily})."
        if monthly > 0 and this_month < monthly and this_month >= monthly * threshold:
            return f"Approaching the monthly image budget ({this_month}/{monthly})."
        return None

    async def record(self) -> None:
        day = datetime.now(UTC).strftime("%Y-%m-%d")
        db = await self._conn()
        try:
            await db.execute(
                "INSERT INTO image_usage (day, count) VALUES (?, 1) "
                "ON CONFLICT(day) DO UPDATE SET count = count + 1",
                (day,),
            )
            await db.commit()
        finally:
            await db.close()


if __name__ == "__main__":
    # ponytail: one runnable check for the budget gate (the only branchy logic here).
    import asyncio
    import tempfile

    async def _demo() -> None:
        with tempfile.TemporaryDirectory() as tmp:
            b = ImageBudget(db_path=str(Path(tmp) / "ig.db"))
            assert await b.check(0, 0) is None  # unlimited
            assert await b.check(2, 0) is None  # under cap
            await b.record()
            await b.record()
            assert await b.usage() == (2, 2)
            assert await b.check(2, 0) is not None  # daily cap hit
            assert await b.check(0, 2) is not None  # monthly cap hit
            assert await b.check(0, 3) is None  # higher monthly cap ok
            for _ in range(6):
                await b.record()  # → 8 today
            assert await b.warning(10, 0) is not None  # 8/10 ≥ 80% → near limit
            assert await b.warning(20, 0) is None  # 8/20 → not near
        print("imagegen.py budget self-check OK")

    asyncio.run(_demo())
